# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lecture_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-order', '-title']},
        ),
    ]
