# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 02:16
from __future__ import unicode_literals

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190124_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=courses.fields.PositionField(default=-1),
        ),
    ]
