# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_mycourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'My course', 'verbose_name_plural': 'My courses'},
        ),
    ]
