# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-25 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_order'),
        ('courses', '0022_auto_20190125_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='secondary',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondary_category', to='category.Category'),
        ),
    ]
