# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
