# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-23 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190123_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='timestampl',
            new_name='timestamp',
        ),
    ]
