# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-25 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
