# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-25 18:37
from __future__ import unicode_literals

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=courses.fields.PositionField(blank=True, default=-1),
        ),
    ]
